// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: forge/v1/tool.proto

package forgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolService_ListTools_FullMethodName    = "/forge.v1.ToolService/ListTools"
	ToolService_DescribeTool_FullMethodName = "/forge.v1.ToolService/DescribeTool"
	ToolService_Invoke_FullMethodName       = "/forge.v1.ToolService/Invoke"
	ToolService_InvokeStream_FullMethodName = "/forge.v1.ToolService/InvokeStream"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ToolService exposes forge's tools.
//
// One service for every tool rather than a generated service per tool. gRPC
// refuses RegisterService after Serve has begun -- it calls Fatalf, which ends
// the process -- so a tool installed while the server is running could never
// get a service of its own. A stable service whose payloads are dynamic is the
// shape that actually survives tools coming and going.
type ToolServiceClient interface {
	// ListTools returns the tools in a view.
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	// DescribeTool returns one tool's schema.
	DescribeTool(ctx context.Context, in *DescribeToolRequest, opts ...grpc.CallOption) (*DescribeToolResponse, error)
	// Invoke runs an operation and returns its result.
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	// InvokeStream runs an operation, reporting the tool's own output and
	// progress as they happen and finishing with the result.
	InvokeStream(ctx context.Context, in *InvokeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeStreamResponse], error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, ToolService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) DescribeTool(ctx context.Context, in *DescribeToolRequest, opts ...grpc.CallOption) (*DescribeToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeToolResponse)
	err := c.cc.Invoke(ctx, ToolService_DescribeTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, ToolService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) InvokeStream(ctx context.Context, in *InvokeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToolService_ServiceDesc.Streams[0], ToolService_InvokeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvokeStreamRequest, InvokeStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_InvokeStreamClient = grpc.ServerStreamingClient[InvokeStreamResponse]

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
//
// ToolService exposes forge's tools.
//
// One service for every tool rather than a generated service per tool. gRPC
// refuses RegisterService after Serve has begun -- it calls Fatalf, which ends
// the process -- so a tool installed while the server is running could never
// get a service of its own. A stable service whose payloads are dynamic is the
// shape that actually survives tools coming and going.
type ToolServiceServer interface {
	// ListTools returns the tools in a view.
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	// DescribeTool returns one tool's schema.
	DescribeTool(context.Context, *DescribeToolRequest) (*DescribeToolResponse, error)
	// Invoke runs an operation and returns its result.
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	// InvokeStream runs an operation, reporting the tool's own output and
	// progress as they happen and finishing with the result.
	InvokeStream(*InvokeStreamRequest, grpc.ServerStreamingServer[InvokeStreamResponse]) error
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedToolServiceServer) DescribeTool(context.Context, *DescribeToolRequest) (*DescribeToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeTool not implemented")
}
func (UnimplementedToolServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedToolServiceServer) InvokeStream(*InvokeStreamRequest, grpc.ServerStreamingServer[InvokeStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method InvokeStream not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call panics, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_DescribeTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).DescribeTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_DescribeTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).DescribeTool(ctx, req.(*DescribeToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_InvokeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToolServiceServer).InvokeStream(m, &grpc.GenericServerStream[InvokeStreamRequest, InvokeStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_InvokeStreamServer = grpc.ServerStreamingServer[InvokeStreamResponse]

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forge.v1.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTools",
			Handler:    _ToolService_ListTools_Handler,
		},
		{
			MethodName: "DescribeTool",
			Handler:    _ToolService_DescribeTool_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _ToolService_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeStream",
			Handler:       _ToolService_InvokeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "forge/v1/tool.proto",
}
