// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: forge/v1/tool.proto

package forgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListToolsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// View names a saved view. Empty means the server's default.
	View          string `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_forge_v1_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{0}
}

func (x *ListToolsRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_forge_v1_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{1}
}

func (x *ListToolsResponse) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

// Tool is one callable operation.
type Tool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is what every forge surface calls this operation, so it matches the
	// MCP tool name and the REST path segment exactly.
	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tool    string   `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Op      string   `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
	Summary string   `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Labels  []string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	// input_schema_json is a JSON Schema document, carried as text.
	//
	// Deliberately not google.protobuf.Struct: Struct's numbers are doubles, so
	// a round trip through it turns "minLength": 3 into 3.0 and mangles any
	// large integer constraint. Clients parse this with a real JSON Schema
	// library anyway.
	InputSchemaJson string `protobuf:"bytes,6,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	OutputKind      string `protobuf:"bytes,7,opt,name=output_kind,json=outputKind,proto3" json:"output_kind,omitempty"`
	OutputMediaType string `protobuf:"bytes,8,opt,name=output_media_type,json=outputMediaType,proto3" json:"output_media_type,omitempty"`
	// requires names the capabilities the tool asks for, so a caller choosing
	// between tools can see that one of them reaches the network.
	Requires      []string `protobuf:"bytes,9,rep,name=requires,proto3" json:"requires,omitempty"`
	ReadOnly      bool     `protobuf:"varint,10,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Destructive   bool     `protobuf:"varint,11,opt,name=destructive,proto3" json:"destructive,omitempty"`
	Idempotent    bool     `protobuf:"varint,12,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_forge_v1_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{2}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Tool) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Tool) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Tool) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Tool) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

func (x *Tool) GetOutputKind() string {
	if x != nil {
		return x.OutputKind
	}
	return ""
}

func (x *Tool) GetOutputMediaType() string {
	if x != nil {
		return x.OutputMediaType
	}
	return ""
}

func (x *Tool) GetRequires() []string {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *Tool) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Tool) GetDestructive() bool {
	if x != nil {
		return x.Destructive
	}
	return false
}

func (x *Tool) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

type DescribeToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeToolRequest) Reset() {
	*x = DescribeToolRequest{}
	mi := &file_forge_v1_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeToolRequest) ProtoMessage() {}

func (x *DescribeToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeToolRequest.ProtoReflect.Descriptor instead.
func (*DescribeToolRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeToolRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *DescribeToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DescribeToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          *Tool                  `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeToolResponse) Reset() {
	*x = DescribeToolResponse{}
	mi := &file_forge_v1_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeToolResponse) ProtoMessage() {}

func (x *DescribeToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeToolResponse.ProtoReflect.Descriptor instead.
func (*DescribeToolResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeToolResponse) GetTool() *Tool {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *DescribeToolResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	View  string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// input is the operation's parameters.
	//
	// Types that are valid to be assigned to Input:
	//
	//	*InvokeRequest_Json
	//	*InvokeRequest_StructValue
	Input         isInvokeRequest_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_forge_v1_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{5}
}

func (x *InvokeRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *InvokeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InvokeRequest) GetInput() isInvokeRequest_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *InvokeRequest) GetJson() []byte {
	if x != nil {
		if x, ok := x.Input.(*InvokeRequest_Json); ok {
			return x.Json
		}
	}
	return nil
}

func (x *InvokeRequest) GetStructValue() *structpb.Struct {
	if x != nil {
		if x, ok := x.Input.(*InvokeRequest_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

type isInvokeRequest_Input interface {
	isInvokeRequest_Input()
}

type InvokeRequest_Json struct {
	// json is the canonical, lossless form, and the one forge's other
	// surfaces use. Prefer it.
	Json []byte `protobuf:"bytes,3,opt,name=json,proto3,oneof"`
}

type InvokeRequest_StructValue struct {
	// struct_value exists so that grpcurl stays pleasant to use. It is LOSSY
	// for integers beyond 2^53, because Struct stores every number as a
	// double; that is documented rather than left to be discovered, and the
	// conformance suite asserts the divergence so it cannot quietly become an
	// undocumented one.
	StructValue *structpb.Struct `protobuf:"bytes,4,opt,name=struct_value,json=structValue,proto3,oneof"`
}

func (*InvokeRequest_Json) isInvokeRequest_Input() {}

func (*InvokeRequest_StructValue) isInvokeRequest_Input() {}

type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// is_error reports that the tool ran and failed.
	//
	// A failed tool is an OK response, not a non-OK status. A status would hide
	// the payload in status.Details(), where most clients never look, and would
	// conflate "the tool said no" with "forge could not run it" -- a distinction
	// every other forge surface keeps.
	IsError bool   `protobuf:"varint,1,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Exactly one of these carries the result, according to output_kind.
	Json      []byte `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	Text      string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Binary    []byte `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"`
	MediaType string `protobuf:"bytes,6,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Stdout    []byte `protobuf:"bytes,7,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr    []byte `protobuf:"bytes,8,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// truncated reports that output hit a cap and was cut, so a caller does not
	// mistake a partial answer for a whole one.
	Truncated     bool  `protobuf:"varint,9,opt,name=truncated,proto3" json:"truncated,omitempty"`
	WallNanos     int64 `protobuf:"varint,10,opt,name=wall_nanos,json=wallNanos,proto3" json:"wall_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_forge_v1_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *InvokeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InvokeResponse) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *InvokeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InvokeResponse) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *InvokeResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *InvokeResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *InvokeResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *InvokeResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *InvokeResponse) GetWallNanos() int64 {
	if x != nil {
		return x.WallNanos
	}
	return 0
}

// InvokeStreamRequest mirrors InvokeRequest.
//
// It is a separate message rather than a reuse so the two calls can evolve
// apart: a field that only makes sense while streaming should not appear in
// the unary request, and vice versa. The duplication is the price of that,
// and it is small.
type InvokeStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	View  string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Input:
	//
	//	*InvokeStreamRequest_Json
	//	*InvokeStreamRequest_StructValue
	Input         isInvokeStreamRequest_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeStreamRequest) Reset() {
	*x = InvokeStreamRequest{}
	mi := &file_forge_v1_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeStreamRequest) ProtoMessage() {}

func (x *InvokeStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeStreamRequest.ProtoReflect.Descriptor instead.
func (*InvokeStreamRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeStreamRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *InvokeStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InvokeStreamRequest) GetInput() isInvokeStreamRequest_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *InvokeStreamRequest) GetJson() []byte {
	if x != nil {
		if x, ok := x.Input.(*InvokeStreamRequest_Json); ok {
			return x.Json
		}
	}
	return nil
}

func (x *InvokeStreamRequest) GetStructValue() *structpb.Struct {
	if x != nil {
		if x, ok := x.Input.(*InvokeStreamRequest_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

type isInvokeStreamRequest_Input interface {
	isInvokeStreamRequest_Input()
}

type InvokeStreamRequest_Json struct {
	Json []byte `protobuf:"bytes,3,opt,name=json,proto3,oneof"`
}

type InvokeStreamRequest_StructValue struct {
	StructValue *structpb.Struct `protobuf:"bytes,4,opt,name=struct_value,json=structValue,proto3,oneof"`
}

func (*InvokeStreamRequest_Json) isInvokeStreamRequest_Input() {}

func (*InvokeStreamRequest_StructValue) isInvokeStreamRequest_Input() {}

// InvokeStreamResponse is one message of a streaming invocation.
type InvokeStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*InvokeStreamResponse_Progress
	//	*InvokeStreamResponse_Log
	//	*InvokeStreamResponse_Result
	Event         isInvokeStreamResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeStreamResponse) Reset() {
	*x = InvokeStreamResponse{}
	mi := &file_forge_v1_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeStreamResponse) ProtoMessage() {}

func (x *InvokeStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeStreamResponse.ProtoReflect.Descriptor instead.
func (*InvokeStreamResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{8}
}

func (x *InvokeStreamResponse) GetEvent() isInvokeStreamResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *InvokeStreamResponse) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Event.(*InvokeStreamResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *InvokeStreamResponse) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Event.(*InvokeStreamResponse_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *InvokeStreamResponse) GetResult() *InvokeResponse {
	if x != nil {
		if x, ok := x.Event.(*InvokeStreamResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isInvokeStreamResponse_Event interface {
	isInvokeStreamResponse_Event()
}

type InvokeStreamResponse_Progress struct {
	Progress *Progress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type InvokeStreamResponse_Log struct {
	Log *LogLine `protobuf:"bytes,2,opt,name=log,proto3,oneof"`
}

type InvokeStreamResponse_Result struct {
	Result *InvokeResponse `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*InvokeStreamResponse_Progress) isInvokeStreamResponse_Event() {}

func (*InvokeStreamResponse_Log) isInvokeStreamResponse_Event() {}

func (*InvokeStreamResponse_Result) isInvokeStreamResponse_Event() {}

type Progress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Done  int64                  `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	// total is zero when the tool does not know how much work there is.
	Total         int64  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_forge_v1_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{9}
}

func (x *Progress) GetDone() int64 {
	if x != nil {
		return x.Done
	}
	return 0
}

func (x *Progress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_forge_v1_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_forge_v1_tool_proto_rawDescGZIP(), []int{10}
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_forge_v1_tool_proto protoreflect.FileDescriptor

const file_forge_v1_tool_proto_rawDesc = "" +
	"\n" +
	"\x13forge/v1/tool.proto\x12\bforge.v1\x1a\x1cgoogle/protobuf/struct.proto\"&\n" +
	"\x10ListToolsRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\"9\n" +
	"\x11ListToolsResponse\x12$\n" +
	"\x05tools\x18\x01 \x03(\v2\x0e.forge.v1.ToolR\x05tools\"\xe4\x02\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06labels\x18\x05 \x03(\tR\x06labels\x12*\n" +
	"\x11input_schema_json\x18\x06 \x01(\tR\x0finputSchemaJson\x12\x1f\n" +
	"\voutput_kind\x18\a \x01(\tR\n" +
	"outputKind\x12*\n" +
	"\x11output_media_type\x18\b \x01(\tR\x0foutputMediaType\x12\x1a\n" +
	"\brequires\x18\t \x03(\tR\brequires\x12\x1b\n" +
	"\tread_only\x18\n" +
	" \x01(\bR\breadOnly\x12 \n" +
	"\vdestructive\x18\v \x01(\bR\vdestructive\x12\x1e\n" +
	"\n" +
	"idempotent\x18\f \x01(\bR\n" +
	"idempotent\"=\n" +
	"\x13DescribeToolRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\\\n" +
	"\x14DescribeToolResponse\x12\"\n" +
	"\x04tool\x18\x01 \x01(\v2\x0e.forge.v1.ToolR\x04tool\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x94\x01\n" +
	"\rInvokeRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x04json\x18\x03 \x01(\fH\x00R\x04json\x12<\n" +
	"\fstruct_value\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x00R\vstructValueB\a\n" +
	"\x05input\"\x8d\x02\n" +
	"\x0eInvokeResponse\x12\x19\n" +
	"\bis_error\x18\x01 \x01(\bR\aisError\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04json\x18\x03 \x01(\fR\x04json\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x16\n" +
	"\x06binary\x18\x05 \x01(\fR\x06binary\x12\x1d\n" +
	"\n" +
	"media_type\x18\x06 \x01(\tR\tmediaType\x12\x16\n" +
	"\x06stdout\x18\a \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\b \x01(\fR\x06stderr\x12\x1c\n" +
	"\ttruncated\x18\t \x01(\bR\ttruncated\x12\x1d\n" +
	"\n" +
	"wall_nanos\x18\n" +
	" \x01(\x03R\twallNanos\"\x9a\x01\n" +
	"\x13InvokeStreamRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x04json\x18\x03 \x01(\fH\x00R\x04json\x12<\n" +
	"\fstruct_value\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x00R\vstructValueB\a\n" +
	"\x05input\"\xac\x01\n" +
	"\x14InvokeStreamResponse\x120\n" +
	"\bprogress\x18\x01 \x01(\v2\x12.forge.v1.ProgressH\x00R\bprogress\x12%\n" +
	"\x03log\x18\x02 \x01(\v2\x11.forge.v1.LogLineH\x00R\x03log\x122\n" +
	"\x06result\x18\x03 \x01(\v2\x18.forge.v1.InvokeResponseH\x00R\x06resultB\a\n" +
	"\x05event\"N\n" +
	"\bProgress\x12\x12\n" +
	"\x04done\x18\x01 \x01(\x03R\x04done\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"9\n" +
	"\aLogLine\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb0\x02\n" +
	"\vToolService\x12D\n" +
	"\tListTools\x12\x1a.forge.v1.ListToolsRequest\x1a\x1b.forge.v1.ListToolsResponse\x12M\n" +
	"\fDescribeTool\x12\x1d.forge.v1.DescribeToolRequest\x1a\x1e.forge.v1.DescribeToolResponse\x12;\n" +
	"\x06Invoke\x12\x17.forge.v1.InvokeRequest\x1a\x18.forge.v1.InvokeResponse\x12O\n" +
	"\fInvokeStream\x12\x1d.forge.v1.InvokeStreamRequest\x1a\x1e.forge.v1.InvokeStreamResponse0\x01B:Z8github.com/richardwooding/forge/grpcapi/forge/v1;forgev1b\x06proto3"

var (
	file_forge_v1_tool_proto_rawDescOnce sync.Once
	file_forge_v1_tool_proto_rawDescData []byte
)

func file_forge_v1_tool_proto_rawDescGZIP() []byte {
	file_forge_v1_tool_proto_rawDescOnce.Do(func() {
		file_forge_v1_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forge_v1_tool_proto_rawDesc), len(file_forge_v1_tool_proto_rawDesc)))
	})
	return file_forge_v1_tool_proto_rawDescData
}

var file_forge_v1_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_forge_v1_tool_proto_goTypes = []any{
	(*ListToolsRequest)(nil),     // 0: forge.v1.ListToolsRequest
	(*ListToolsResponse)(nil),    // 1: forge.v1.ListToolsResponse
	(*Tool)(nil),                 // 2: forge.v1.Tool
	(*DescribeToolRequest)(nil),  // 3: forge.v1.DescribeToolRequest
	(*DescribeToolResponse)(nil), // 4: forge.v1.DescribeToolResponse
	(*InvokeRequest)(nil),        // 5: forge.v1.InvokeRequest
	(*InvokeResponse)(nil),       // 6: forge.v1.InvokeResponse
	(*InvokeStreamRequest)(nil),  // 7: forge.v1.InvokeStreamRequest
	(*InvokeStreamResponse)(nil), // 8: forge.v1.InvokeStreamResponse
	(*Progress)(nil),             // 9: forge.v1.Progress
	(*LogLine)(nil),              // 10: forge.v1.LogLine
	(*structpb.Struct)(nil),      // 11: google.protobuf.Struct
}
var file_forge_v1_tool_proto_depIdxs = []int32{
	2,  // 0: forge.v1.ListToolsResponse.tools:type_name -> forge.v1.Tool
	2,  // 1: forge.v1.DescribeToolResponse.tool:type_name -> forge.v1.Tool
	11, // 2: forge.v1.InvokeRequest.struct_value:type_name -> google.protobuf.Struct
	11, // 3: forge.v1.InvokeStreamRequest.struct_value:type_name -> google.protobuf.Struct
	9,  // 4: forge.v1.InvokeStreamResponse.progress:type_name -> forge.v1.Progress
	10, // 5: forge.v1.InvokeStreamResponse.log:type_name -> forge.v1.LogLine
	6,  // 6: forge.v1.InvokeStreamResponse.result:type_name -> forge.v1.InvokeResponse
	0,  // 7: forge.v1.ToolService.ListTools:input_type -> forge.v1.ListToolsRequest
	3,  // 8: forge.v1.ToolService.DescribeTool:input_type -> forge.v1.DescribeToolRequest
	5,  // 9: forge.v1.ToolService.Invoke:input_type -> forge.v1.InvokeRequest
	7,  // 10: forge.v1.ToolService.InvokeStream:input_type -> forge.v1.InvokeStreamRequest
	1,  // 11: forge.v1.ToolService.ListTools:output_type -> forge.v1.ListToolsResponse
	4,  // 12: forge.v1.ToolService.DescribeTool:output_type -> forge.v1.DescribeToolResponse
	6,  // 13: forge.v1.ToolService.Invoke:output_type -> forge.v1.InvokeResponse
	8,  // 14: forge.v1.ToolService.InvokeStream:output_type -> forge.v1.InvokeStreamResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_forge_v1_tool_proto_init() }
func file_forge_v1_tool_proto_init() {
	if File_forge_v1_tool_proto != nil {
		return
	}
	file_forge_v1_tool_proto_msgTypes[5].OneofWrappers = []any{
		(*InvokeRequest_Json)(nil),
		(*InvokeRequest_StructValue)(nil),
	}
	file_forge_v1_tool_proto_msgTypes[7].OneofWrappers = []any{
		(*InvokeStreamRequest_Json)(nil),
		(*InvokeStreamRequest_StructValue)(nil),
	}
	file_forge_v1_tool_proto_msgTypes[8].OneofWrappers = []any{
		(*InvokeStreamResponse_Progress)(nil),
		(*InvokeStreamResponse_Log)(nil),
		(*InvokeStreamResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forge_v1_tool_proto_rawDesc), len(file_forge_v1_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forge_v1_tool_proto_goTypes,
		DependencyIndexes: file_forge_v1_tool_proto_depIdxs,
		MessageInfos:      file_forge_v1_tool_proto_msgTypes,
	}.Build()
	File_forge_v1_tool_proto = out.File
	file_forge_v1_tool_proto_goTypes = nil
	file_forge_v1_tool_proto_depIdxs = nil
}
